using System;
using Hearthdelve.Shared.Ingredients;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Settings;

namespace Hearthdelve.UI.Localization
{
    /// <summary>
    /// String-table lookups for player-facing text. Every visible string goes through here
    /// (CLAUDE.md: no literal UI text in C# or UXML). Missing keys render as the key itself
    /// so they're obvious in playtests.
    /// </summary>
    public static class Loc
    {
        public const string UITable = "UI";
        public const string ContentTable = "Content";

        public static string UI(string key, params object[] args) => Get(UITable, key, args);

        public static string Get(string table, string key, params object[] args)
        {
            try
            {
                var value = args != null && args.Length > 0
                    ? LocalizationSettings.StringDatabase.GetLocalizedString(table, key, args)
                    : LocalizationSettings.StringDatabase.GetLocalizedString(table, key);
                return string.IsNullOrEmpty(value) ? $"#{key}" : value;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"Localization lookup failed for {table}/{key}: {e.Message}");
                return $"#{key}";
            }
        }

        public static string Get(LocalizedString text)
        {
            if (text == null || text.IsEmpty) return "#missing";
            try { return text.GetLocalizedString(); }
            catch (Exception) { return "#missing"; }
        }

        public static string Quality(Quality quality) => UI(quality switch
        {
            Shared.Ingredients.Quality.Poor => LocKeys.QualityPoor,
            Shared.Ingredients.Quality.Standard => LocKeys.QualityStandard,
            Shared.Ingredients.Quality.Fine => LocKeys.QualityFine,
            _ => LocKeys.QualityPremium,
        });

        /// <summary>Empty for Raw (not worth a label).</summary>
        public static string Prep(PrepState prep) => prep switch
        {
            PrepState.Seared => UI(LocKeys.PrepSeared),
            PrepState.Chilled => UI(LocKeys.PrepChilled),
            PrepState.Inedible => UI(LocKeys.PrepInedible),
            _ => string.Empty,
        };

        /// <summary>"Fine Rat Haunch" / "Fine Rat Haunch (Seared)".</summary>
        public static string ItemName(IngredientItem item)
        {
            if (!item.IsValid) return string.Empty;
            string name = Get(item.Definition.displayName);
            string quality = Quality(item.Quality);
            string prep = Prep(item.Prep);
            return string.IsNullOrEmpty(prep)
                ? UI(LocKeys.ItemFormat, quality, name)
                : UI(LocKeys.ItemFormatPrep, quality, name, prep);
        }
    }

    /// <summary>Keys in the UI string table. The table itself is generated by Hearthdelve/Setup/Localization.</summary>
    public static class LocKeys
    {
        public const string HudEssence = "hud.essence";
        public const string HudSatchel = "hud.satchel";
        public const string HudSatchelFull = "hud.satchel_full";

        public const string HarvestCleanKill = "harvest.clean_kill";
        public const string HarvestOverkill = "harvest.overkill";
        public const string HarvestDestroyed = "harvest.destroyed";
        public const string HarvestFinisher = "harvest.finisher";
        public const string HarvestGot = "harvest.got";

        public const string QualityPoor = "quality.poor";
        public const string QualityStandard = "quality.standard";
        public const string QualityFine = "quality.fine";
        public const string QualityPremium = "quality.premium";

        public const string PrepSeared = "prep.seared";
        public const string PrepChilled = "prep.chilled";
        public const string PrepInedible = "prep.inedible";

        public const string ItemFormat = "item.format";
        public const string ItemFormatPrep = "item.format_prep";
        public const string SlotEmpty = "slot.empty";
        public const string SlotCount = "slot.count";

        public const string DeathTitle = "death.title";
        public const string DeathSubtitle = "death.subtitle";
        public const string DeathSubtitleEmpty = "death.subtitle_empty";
        public const string DeathSelected = "death.selected";
        public const string DeathSelectedNone = "death.selected_none";
        public const string DeathConfirm = "death.confirm";
        public const string DeathKeepNothing = "death.keep_nothing";

        public const string SwapTitle = "swap.title";
        public const string SwapSubtitle = "swap.subtitle";
        public const string SwapCancel = "swap.cancel";

        /// <summary>Every key with its English text. Used by the editor to build the table.</summary>
        public static readonly (string key, string english)[] English =
        {
            (HudEssence, "Essence"),
            (HudSatchel, "Satchel"),
            (HudSatchelFull, "Satchel full — press {0} to swap"),

            (HarvestCleanKill, "Clean kill!"),
            (HarvestOverkill, "Overkill!"),
            (HarvestDestroyed, "{0} was destroyed"),
            (HarvestFinisher, "Finisher!"),
            (HarvestGot, "{0} ×{1}"),

            (QualityPoor, "Poor"),
            (QualityStandard, "Standard"),
            (QualityFine, "Fine"),
            (QualityPremium, "Premium"),

            (PrepSeared, "Seared"),
            (PrepChilled, "Chilled"),
            (PrepInedible, "Inedible"),

            (ItemFormat, "{0} {1}"),
            (ItemFormatPrep, "{0} {1} ({2})"),
            (SlotEmpty, "Empty"),
            (SlotCount, "×{0}"),

            (DeathTitle, "Your Essence Fades"),
            (DeathSubtitle, "The dungeon casts you back to the surface. Choose one slot to save in your Lockbox — its whole stack is kept, the rest of the haul is lost."),
            (DeathSubtitleEmpty, "The dungeon casts you back to the surface. Your satchel is empty."),
            (DeathSelected, "Lockbox: {0} ×{1}"),
            (DeathSelectedNone, "Lockbox: nothing"),
            (DeathConfirm, "Return to the surface"),
            (DeathKeepNothing, "Keep nothing"),

            (SwapTitle, "Satchel Full"),
            (SwapSubtitle, "Found {0} ×{1}. Choose a slot to drop for it."),
            (SwapCancel, "Leave it"),
        };
    }
}
